os: linux
language: cpp
compiler: g++

branches:
  only:
    - devel
    - /^v\d+\.\d+\.\d+.*$/

env:
  - DISTRIBUTION=python
  # - DISTRIBUTION=conda

jobs:
  include:
    - dist: focal
    # - dist: bionic

services:
  - docker
  
notifications:
  email:
    recipients:
      - francesco.ruscelli@iit.it
      - arturo.laurenzi@iit.it
      - enrico.mingo@pal-robotics.com
    on_success: never
    on_failure: never

before_install:
  - rm -rf /opt/pyenv

before_script:
  - export SRC_DIR=$PWD 
  - export BUILD_DIR=$PWD/build
  - export FOREST_DIR=$PWD/../forest_ws 
  - export HORIZON_DIR=$FOREST_DIR/src/horizon

  - ./travis/init.sh

script:

# required packages for building horizon
  # - FOREST_ARGS="--default-build-type Release --clone-protocol https --verbose -j2"
  # - cd $FOREST_DIR

# required!
  # - source setup.bash

  # - forest casadi $FOREST_ARGS
  # - forest pybind11 $FOREST_ARGS

  # - echo $CMAKE_PREFIX_PATH

  # - cd $HORIZON_DIR
  # - pip3 install -v .

  # - cd $FOREST_DIR && source setup.bash
  # - ./travis/python_run.sh
  - ./travis/run.sh
