os: linux
language: cpp
compiler: g++

branches:
  only:
    - devel
    - /^v\d+\.\d+\.\d+.*$/

env:
  - DISTRIBUTION=python
  - DISTRIBUTION=conda

dist:
  - focal
  - bionic

# jobs:
#   include:
#     - dist: focal
#     - dist: bionic

services:
  - docker
  
notifications:
  email:
    recipients:
      - francesco.ruscelli@iit.it
      - arturo.laurenzi@iit.it
      - enrico.mingo@pal-robotics.com
    on_success: never
    on_failure: never

before_install:
  - rm -rf /opt/pyenv

before_script:
  - export SRC_DIR=$PWD 
  - export BUILD_DIR=$PWD/build
  - export FOREST_DIR=$PWD/../forest_ws 
  - export HORIZON_DIR=$FOREST_DIR/src/horizon

  - ./travis/init.sh

script:

  - ./travis/run.sh
