os: linux
language: cpp
compiler: g++

dist: 
- focal
- bionic

branches:
  only:
    - devel
    # - /^v\d+\.\d+\.\d+.*$/  # version tags


jobs:
  include:
    - stage: compile
      script: ./travis/python_compile.sh
      dist: focal
    -
      script: ./travis/python_compile.sh
      dist: bionic
      # ----
    - stage: test
      script: ./travis/test.sh
      dist: focal
    - 
      script: ./travis/test.sh
      dist: bionic
      # ----
    - stage: deploy
      script: ./travis/deploy.sh
      dist: focal
      if: branch = devel AND tag IS present
    - 
      script: ./travis/deploy.sh
      tags: true
      dist: bionic
      if: branch = devel AND tag IS present

  
services:
  - docker
  
notifications:
  email:
    recipients:
      - francesco.ruscelli@iit.it
      - arturo.laurenzi@iit.it
      - enrico.mingo@pal-robotics.com
    on_success: never
    on_failure: never

before_install:
  - rm -rf /opt/pyenv

before_script:
  - export SRC_DIR=$PWD 
  - export BUILD_DIR=$PWD/build 
  - export FOREST_DIR=$PWD/../forest_ws 
  - export HORIZON_DIR=$FOREST_DIR/src/horizon
  - ./travis/init.sh
  - ./travis/forest.sh