os: linux
language: cpp
compiler: g++

dist: 
- focal
- bionic

branches:
  only:
    - devel
    # - /^v\d+\.\d+\.\d+.*$/  # version tags

jobs:
  include:
    - stage: compile
      script: ./travis/python_compile.sh
      dist: focal
    -
      script: ./travis/python_compile.sh
      dist: bionic
      # ----
    - stage: test
      script: ./travis/test.sh
      dist: focal
    - 
      script: ./travis/test.sh
      dist: bionic
      # ----
    - stage: deploy
      script: ./travis/deploy.sh
      on:
        tags: true
      dist: focal
    - 
      script: ./travis/deploy.sh
      on:
        tags: true
      dist: bionic


services:
  - docker
  
notifications:
  email:
    recipients:
      - francesco.ruscelli@iit.it
      - arturo.laurenzi@iit.it
      - enrico.mingo@pal-robotics.com
    on_success: never
    on_failure: always

before_install:
  - rm -rf /opt/pyenv

before_script:
  - ./travis/forest.sh